version: '3.5'
services:
  busybox:
    image: registry.cn-guangzhou.aliyuncs.com/tomhjx/mirrorspro:tomhjx_busybox.playwright-python
    privileged: true
    restart: always
    volumes:
      - ./:/work
    command:
      - sleep
      - "10000000"
    cap_add:
      - ALL
networks:
  default:
    name: lab
