version: '3.5'
services:
  busybox:
    build: ./docker/alpine3.18
    privileged: true
    restart: always
    command:
      - sleep
      - "10000000"
    cap_add:
      - ALL
networks:
  default:
    name: lab
